seoulrobotics/sensr_sdk

- proto/sensr_proto/output.proto
- proto/sensr_proto/rest_api.proto
- proto/sensr_proto/type.proto
Do you want to leave the comments or remove them?
> sync proto files - tracking_status and timestamp

- samples/console_output/main.cpp
- Add Health check example.
- Update proto field changing. (time_stamp -> timestamp)
> Add health check example and change time_stamp to timestamp.

- python/sensr_message_listener.py
- Add disconnect interface in MessageListener.
This will be used for auto testing.
Sample usage code is https://seoulrobotics.atlassian.net/l/c/BPZfG9TL.
> add disconnect interface in python sdk.

- proto/CMakeLists.txt
It is convenient for us to deploy the library.
> Use static protobuf library

- include/sensr_client.h
- javascript/javascript_sdk/src/sensr_client.js
- python/console_output.py
- python/save_load_output.py
- python/sensr_message_listener.py
- samples/console_output/main.cpp
- samples/imgui_display/main.cpp
- samples/output_recorder/main.cpp
- src/sensr_client.cpp
- src/websocket_endpoint.cpp
- src/websocket_endpoint.h
> Disable WSS

- CMakeLists.txt
- src/sensr_message_listener.cpp
Add cmake option for giving choice whether turning on output log message or not.
> Add selective log message

- CMakeLists.txt
- src/logging.h
- src/sensr_message_listener.cpp
- src/websocket_endpoint.cpp
> More option of logging

- proto/README.md
> Update Readme to add zone_ids

- CMakeLists.txt
I just realized that option command use bool.
https://cmake.org/cmake/help/latest/command/option.html?highlight=option
So I replaced the level structure.
> use bool instead of integer

- python/console_output.py
- python/sensr_message_listener.py
- Check websocket connection is closed or not when `CTRL+ C` comes.
This removes `[error] handle_read_frame error: websocketpp.transport:7 (End of File)` message in SENSR.
> Add disconnect interface and check websocket close in there.

- python/console_output.py
- python/sensr_message_listener.py
- samples/console_output/main.cpp
- Apply new history message format.
- Fix a bug in python script which never stop disconnect() function if the function is called in the inherited class.
> Apply new history

- proto/README.md
> Update readme proto

- .gitmodules
- javascript/javascript_sdk/src/get_data.js
- python/console_output.py
- samples/console_output/main.cpp
More information when printing object
> more output in sdk

- .gitmodules
- CMakeLists.txt
- README.md
- src/websocket/websocket_secure_endpoint.cpp
- Remove boost dependency
- Add asio submodule (websocket tls has asio dependency.)
- Better readme.
> Remove boost dep

- python/console_output.py
- python/console_output_secure.py
- python/sensr_message_listener.py
- Temporary rollback all the reconnect related codes in python because of CI server error.
> Rollback all the reconnect related codes  in python

- include/sensr_client.h
- src/sensr_client.cpp
- src/websocket/websocket_endpoint_base.h
- Fix infinite stacking Reconnect() in call stack.
- Make a thread in order to re-connection and do not request it if it's running.
> Make SDK to reconnect to SENSR when SENSR is re-opened.

- javascript/javascript_sdk/src/get_data.js
- python/console_output.py
- python/requirements.txt
- samples/console_output/main.cpp
- Update submodule to include intensity for point clouds and object points
- Update python example to show how to get intensity (we can update the C++ and javascript examples later)
https://seoulrobotics.atlassian.net/browse/AR-4149
> Include point intensity

- README.md
- Fix missing argument in `git submodule` command in readme.
> Add missing text in readme.md

- proto/README.md
- Update explanation of proto file fields
https://github.com/seoulrobotics/sensr_sdk/tree/update-proto-readme/proto
> Update readme of proto files.

- python/console_output.py
- python/console_output_secure.py
- python/sensr_message_listener.py
* utilize `has_objects` in object listener
* handle case when output_ws is `None`
> 2.4.9 update

- README.md
add installation of missing dependencies (cmake, libssl, libz) for cpp sdk
> add installation of missing dependencies for cmake, ssl, and zlib

- python/configure.sh
- fix - potential error when downloaded protoc archive is not a valid zip file
- lint - fix shellcheck 2250 [SC2250](https://www.shellcheck.net/wiki/SC2250)
> Fix local download

- javascript/javascript_sdk/src/get_data.js
- samples/console_output/main.cpp
Changes:
* update sensr_proto submodule to latest version
* fix printing sensor health status in example code for python, javascript, and cpp sdk
* fix receiving printing profiling information in cpp example code
> update sensr_proto module
